### ISSUE TITLE
not compatible with jQueryUI1.10, hence 1.11, coming

### ISSUE THREAD

**Issue by mLaird** [nostrademons/jquery-combobox#4]
Things work fine with jQueryUI1.9.2.  As I tried to migrate to 1.10, I get the following error in the Console, and my page won't even load.
TypeError: $.widget is not a function
[Break On This Error]  
finishSelection: function(index, e) {
ui.combobox.js (line 344)
$.widget has changed in 1.10, and the old code will be removed in 1.11. Please make the upgrade, and let me know when completed, so I can upgrade my page.
mlaird (at) alum [dot] mit (dot) edu
thanks
